### ISSUE TITLE
量子传输站bug

### ISSUE THREAD

**Issue by wududu123** [blacksnipebiu/Multifunction_mod#2]
目前发现量子传输站无法正确的处理有机晶体。
有机晶体在供应时无故消失了，按p看到，生产/消耗比为4：1左右，但是量子传输站里面没有库存的有机晶体。
测试了下，只有同时开启组装机供应和组装机拿取才有这个bug，只开启开启组装机供应没有问题。

**Comment by blacksnipebiu** [comment]
你是否开了“物流站内置发电”，并且把有机晶体放在了第五格。又或者是安装了单独的星球矿机mod，并将有机晶体放在了第四格

**Comment by blacksnipebiu** [comment]
我这边测试了一下，没有出现你所说的问题，你根据我上述的情况检查一下，如果不存在这两种情况，请给我一个完整点的复现流程
