### ISSUE TITLE
(无关紧要的小问题)thurderstore 网站链接错误

### ISSUE THREAD

**Issue by newbienoobplayer** [blacksnipebiu/Multifunction_mod#4]
![Screenshot (478)](https://github.com/blacksnipebiu/Multifunction_mod/assets/138718840/4f62cbbf-60ac-4ad8-91cc-da624a1abe1e)
![image](https://github.com/blacksnipebiu/Multifunction_mod/assets/138718840/a68ea85b-9dc1-4536-962c-b37945739c25)

大佬你 thurderstore 里面的链接无法正确的到达 github 的 Multifunction mod 页面(我是靠谷歌来的)
https://dsp.thunderstore.io/package/blacksnipebiu/Multfuntion_mod/

(我差点以为mod 被封了)

**Comment by blacksnipebiu** [comment]
好的，等下次版本更新就把正确的名字换上去

**Comment by newbienoobplayer** [comment]
mod很好 加油

**Comment by newbienoobplayer** [comment]
比CE 方便多了, 就是小飞机飞行速度上限有点低
