### ISSUE TITLE
功能缺失(好像)

### ISSUE THREAD

**Issue by newbienoobplayer** [blacksnipebiu/Multifunction_mod#5]
这是说明书(https://www.bilibili.com/read/cv15188863/) 里面说有修改采矿速度和制造速度的选项
![image](https://github.com/blacksnipebiu/Multifunction_mod/assets/138718840/c0ed67bf-8637-470a-903a-717fde5601aa)

这是我的截图,为啥没有啊,我是少安装了什么嘛?,有办法让我手动调整数值吗?
![image](https://github.com/blacksnipebiu/Multifunction_mod/assets/138718840/a80f530e-728e-4481-b85a-ee8a5613a831)

还有不知道为什么 我改不了运输船的载量

**Comment by blacksnipebiu** [comment]
采矿速度和制造速度在右边,现在直接MAX了不需要调数值了.运输船载量你需要点右边的启动修改

**Comment by newbienoobplayer** [comment]
运输船我有点启用修改但是每次保存完存档之后再进入就会变回原样

**Comment by blacksnipebiu** [comment]
我这边测试了，修改运输船载量后保存，重新载入是有记录的啊

**Comment by newbienoobplayer** [comment]
[LogOutput.log](https://github.com/blacksnipebiu/Multifunction_mod/files/12503677/LogOutput.log)

这是我的 log 能不能帮我看一下是哪一个mod不兼容导致 重新载入后没有改变,谢谢

**Comment by blacksnipebiu** [comment]
这不在我的调试范围内啊，我只能保证单mod情况下功能不失效，你这么多mod，功能冲突的话我也没办法

**Comment by newbienoobplayer** [comment]
好哒,谢谢大佬
