### ISSUE TITLE
通过【点击生成中继器】方式生成的全都属于同一个黑雾巢穴

### ISSUE THREAD

**Issue by jessefjxm** [blacksnipebiu/Multifunction_mod#7]
一个星系可能有3或6个巢穴，能否在生成时按顺序或者随机指定一个巢穴？我现在在黑洞星球上面建了6个刷怪基地，目前6个基地都属于α巢穴，如果能每个基地各自属于一个巢穴就好了。

**Comment by blacksnipebiu** [comment]
所以是为了什么呢

**Comment by jessefjxm** [comment]
> 所以是为了什么呢

就是想让每个基地各自对应一个黑雾巢穴，这样一个巢穴养一个基地，不容易饿死

**Comment by blacksnipebiu** [comment]
那我把新增的中继器分配给拥有中继器最少的巢穴如何

**Comment by jessefjxm** [comment]
> 那我把新增的中继器分配给拥有中继器最少的巢穴如何

感觉挺好，赞
