### ISSUE TITLE
开启极速弹射器后新建的弹射器内自带 2^31-1 太阳帆

### ISSUE THREAD

**Issue by Sakura1618** [blacksnipebiu/Multifunction_mod#8]
mod 版本：3.4.5
游戏版本：0.10.30.23430

复现：
开启极速轨道弹射器
建造新的弹射器
面板中显示 2^31-1 太阳帆

![967bf257b8f6fedfe80db690dd4261f3](https://github.com/user-attachments/assets/f628c1ce-caa7-413e-b11e-399deaf572b1)

**Comment by blacksnipebiu** [comment]
这就是从一开始就弄了的设定，故意的

**Comment by Sakura1618** [comment]
记得黑雾更新前是不添加太阳帆来着

**Comment by blacksnipebiu** [comment]
一直都有，做这个功能开始就有的

**Comment by Sakura1618** [comment]
感谢您的回复，确实是我记错了，UXAssist Mod 有相似的功能，它不会添加太阳帆。
